In [2]:
import numpy as np
import pandas as pd
import json

In [ ]:
with open('t_20_json/match_results.json') as f :
    data = json.load(f) 


df_match = pd.DataFrame(data[0]['matchSummary'])
df_match

,team1,team2,winner,margin,ground,matchDate,scorecard
0,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879
1,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
2,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
3,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
4,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
5,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
6,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
7,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
8,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
9,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
10,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
11,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
12,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
13,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
14,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
15,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
16,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
17,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
18,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
19,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
20,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
23,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
24,South Africa,Zimbabwe,no result,-,Hobart,"Oct 24, 2022",T20I # 1844
25,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
26,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
27,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
28,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
29,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
30,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
31,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
32,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
33,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
34,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
35,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
36,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
37,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
38,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
39,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
40,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
41,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823

In [4]:
df_match.rename({'scorecard': 'match_id'} , axis = 1 , inplace = True)
df_match

,team1,team2,winner,margin,ground,matchDate,match_id
0,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879
1,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
2,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
3,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
4,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
5,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
6,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
7,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
8,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
9,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
10,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
11,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
12,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
13,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
14,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
15,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
16,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
17,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
18,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
19,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
20,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
23,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
24,South Africa,Zimbabwe,no result,-,Hobart,"Oct 24, 2022",T20I # 1844
25,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
26,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
27,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
28,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
29,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
30,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
31,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
32,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
33,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
34,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
35,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
36,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
37,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
38,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
39,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
40,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
41,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823

In [ ]:
df_match.to_csv('t_20_csv/dim_match_summary.csv' , index = False)

match_ids_dict = {} 

for index, row in df_match.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']
    
    match_ids_dict[key1] = row['match_id']
    match_ids_dict[key2] = row['match_id']
match_ids_dict

In [ ]:
with open('t_20_json/batting_summary.json') as f :
    data = json.load(f)

all_records = []
for rec in data:
    all_records.extend(rec['battingSummary'])

df_batting = pd.DataFrame(all_records)
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00

In [8]:
df_batting['out/not_out'] = df_batting.dismissal.apply(lambda x: "out" if len(x) > 0 else "not_out")
df_batting.drop(columns = ['dismissal'] , inplace = True)
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out

In [9]:
df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x: x.replace('â€', ''))
df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x: x.replace('\xa0', ''))
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out

In [10]:
df_batting["match_id"] = df_batting["match"].map(match_ids_dict)
df_batting.head(50)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out,T20I # 1823
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out,T20I # 1823
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out,T20I # 1823
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out,T20I # 1823
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out,T20I # 1823
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out,T20I # 1823
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out,T20I # 1823
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out,T20I # 1823
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out,T20I # 1823
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out,T20I # 1823
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out,T20I # 1823
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out,T20I # 1823
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out,T20I # 1823
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out,T20I # 1823
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,not_out,T20I # 1823
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out,T20I # 1825
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out,T20I # 1825
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out,T20I # 1825
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out,T20I # 1825
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out,T20I # 1825
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out,T20I # 1825
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out,T20I # 1825
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out,T20I # 1825
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,not_out,T20I # 1825
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,not_out,T20I # 1825
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out,T20I # 1825
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out,T20I # 1825
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out,T20I # 1825
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out,T20I # 1825
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out,T20I # 1825
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c),16,19,0,0,84.21,not_out,T20I # 1825
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out,T20I # 1825
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out,T20I # 1825
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,not_out,T20I # 1825
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,not_out,T20I # 1826
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out,T20I # 1826
40,Scotland Vs West Indies,Scotland,3,Matthew Cross,3,5,0,0,60.00,out,T20I # 1826
41,Scotland Vs West Indies,Scotland,4,Richie Berrington(c),16,14,0,1,114.28,out,T20I # 1826
42,Scotland Vs West Indies,Scotland,5,Calum MacLeod,23,14,4,0,164.28,out,T20I # 1826
43,Scotland Vs West Indies,Scotland,6,Michael Leask,4,6,0,0,66.66,out,T20I # 1826
44,Scotland Vs West Indies,Scotland,7,Chris Greaves,16,11,2,0,145.45,not_out,T20I # 1826
45,Scotland Vs West Indies,West Indies,1,Kyle Mayers,20,13,3,1,153.84,out,T20I # 1826
46,Scotland Vs West Indies,West Indies,2,Evin Lewis,14,13,1,1,107.69,out,T20I # 1826
47,Scotland Vs West Indies,West Indies,3,Brandon King,17,15,3,0,113.33,out,T20I # 1826
48,Scotland Vs West Indies,West Indies,4,Nicholas Pooran(c),5,9,0,0,55.55,out,T20I # 1826
49,Scotland Vs West Indies,West Indies,5,Shamarh Brooks,4,9,0,0,44.44,out,T20I # 1826

In [ ]:
df_batting.to_csv('t_20_csv/fact_batting_summary.csv' , index = False)

In [ ]:
with open('t_20_json/bowling_summary.json') as f: 
    data = json.load(f)
all_records = [] 

for rec in data:
    all_records.extend(rec["bowlingSummary"])

df_bowling = pd.DataFrame(all_records)
df_bowling

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Pakistan Vs England,Pakistan,Naseem Shah,4,0,30,0,7.50,15,3,1,1,0
496,Pakistan Vs England,Pakistan,Haris Rauf,4,0,23,2,5.75,13,3,0,1,0
497,Pakistan Vs England,Pakistan,Shadab Khan,4,0,20,1,5.00,10,1,0,0,0
498,Pakistan Vs England,Pakistan,Mohammad Wasim,4,0,38,1,9.50,5,5,0,2,0
499,Pakistan Vs England,Pakistan,Iftikhar Ahmed,0.5,0,13,0,15.60,0,1,1,0,0

In [13]:
df_bowling["match_id"] = df_bowling["match"].map(match_ids_dict)
df_bowling.head(20)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0,T20I # 1823
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0,T20I # 1823
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0,T20I # 1823
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0,T20I # 1823
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0,T20I # 1823
10,Namibia Vs Sri Lanka,Namibia,Jan Frylinck,4,0,26,2,6.50,10,0,2,1,0,T20I # 1823
11,U.A.E. Vs Netherlands,Netherlands,Fred Klaassen,4,0,13,2,3.25,18,0,0,3,0,T20I # 1825
12,U.A.E. Vs Netherlands,Netherlands,Tim Pringle,4,0,13,1,3.25,11,0,0,0,0,T20I # 1825
13,U.A.E. Vs Netherlands,Netherlands,Logan van Beek,2,0,19,0,9.50,5,0,2,1,0,T20I # 1825
14,U.A.E. Vs Netherlands,Netherlands,Bas de Leede,3,0,19,3,6.33,9,2,0,2,0,T20I # 1825
15,U.A.E. Vs Netherlands,Netherlands,Paul van Meekeren,4,0,21,0,5.25,11,1,0,0,0,T20I # 1825
16,U.A.E. Vs Netherlands,Netherlands,Roelof van der Merwe,3,0,19,1,6.33,7,0,1,0,0,T20I # 1825
17,U.A.E. Vs Netherlands,U.A.E.,Junaid Siddique,4,0,24,3,6.00,10,2,0,1,0,T20I # 1825
18,U.A.E. Vs Netherlands,U.A.E.,Basil Hameed,1,0,7,1,7.00,4,0,1,0,0,T20I # 1825
19,U.A.E. Vs Netherlands,U.A.E.,Aayan Afzal Khan,3,0,15,1,5.00,8,1,0,0,0,T20I # 1825

In [ ]:
df_bowling.to_csv('t_20_csv/fact_bowling_summary.csv' , index = False)

In [ ]:
with open('t_20_json/player_info.json') as f:
    data = json.load(f)

In [16]:
df_players = pd.DataFrame(data)
df_players.head(40)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendisâ€,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka(c),Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
20,Bernard Scholtz,Namibia,Right hand Bat,Slow Left arm Orthodox,Bowler,Bernard Scholtz's brother Nicolaas is currentl...
21,Ben Shikongo,Namibia,Right hand Bat,Right arm Medium fast,Bowler,
22,Charith Asalanka,Sri Lanka,Left hand Bat,Right arm Offbreak,Batting Allrounder,
23,David Warner,Australia,Left hand Bat,Legbreak,Opening Batter,David Warner's extraordinary batting feats in ...
24,Aaron Finch(c),Australia,Right hand Bat,Slow Left arm Orthodox,Top order Batter,"A solidly built, aggressive batter from a coun..."
25,Mitchell Marsh,Australia,Right hand Bat,Right arm Medium,Allrounder,Part of one of the most well-known family name...
26,Glenn Maxwell,Australia,Right hand Bat,Right arm Offbreak,Batting Allrounder,"One of the fastest scorers in world cricket, G..."
27,Marcus Stoinis,Australia,Right hand Bat,Right arm Medium,Batting Allrounder,"A powerful, versatile batter and medium-pace b..."
28,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,A tall and accurate fast bowler who is unrelen...
29,Pat Cummins,Australia,Right hand Bat,Right arm Fast,Bowler,Earmarked as a potential star from a young age...
30,Mitchell Starc,Australia,Left hand Bat,Left arm Fast,Bowler,"First there was Johnson, then there was Starc...."
31,Ashton Agar,Australia,Left hand Bat,Slow Left arm Orthodox,Bowler,Ashton Agar initially turned almost as many he...
32,Binura Fernando,Sri Lanka,Right hand Bat,Left arm Medium fast,Bowler,Known for his ability to generate awkward boun...
33,Lahiru Kumara,Sri Lanka,Left hand Bat,Right arm Fast,Bowler,"A robust, right-arm fast bowler from Kandy, La..."
34,Dasun Shanaka,Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
35,Regis Chakabvaâ€,Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
36,Craig Ervine(c),Zimbabwe,Left hand Bat,Right arm Offbreak,Middle order Batter,Few people in Zimbabwe cricket circles were su...
37,Wessly Madhevere,Zimbabwe,Right hand Bat,Right arm Offbreak,Allrounder,
38,Sean Williams,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Middle order Batter,"Sean Williams is a bold, dynamic left-hand bat..."
39,Sikandar Raza,Zimbabwe,Right hand Bat,Right arm Offbreak,Batting Allrounder,Sikandar Raza's story isn't that of your every...

In [17]:
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('†', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0', ''))
df_players.head(10)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."

In [ ]:
df_players.to_csv('t_20_csv/dim_player_no_images.csv', index = False)